### ISSUE TITLE
UI - Upload Ad

### ISSUE THREAD

**Issue by asifjans** [asifjans/Inovedia#38]

**Comment by asifjans** [comment]
1. When user clicks on "Upload Ad" button then he will be redirected to "Upload Ad" page from User's account.
2. User must give details of car including Ad Title, Description, Cities, Car Make, Model, Year range, Mileage range, Price range (Ticket Price), Transmission Type, Color, Fuel Type, Regional Specs, Warranty, Service History, Pictures, Price.
3. After I have accepted the form then pop up should appear telling that ad is not live yet and I have to wait for approval. And email should be sent to Admin about adding ad.
4. Email from admin is then sent to user of proposed price of the car. 
5. If user accept the proposal then Ad will get live. 
6. If user don't accept the proposal then user will be visited for finalizing the price.
7. After finalizig the price ad should get live and should be visible on View cars page.
8. Ad should be live, after price gets finalized, for seven days so that user can get the desired price.
9. If user does not get the desired price till the ad expiry date reached then he will be given offer so that he can decide whether to accept or reject that offer.
10. If user doesn't agree to the offered price then ad should be extended or deleted based on what user decides.

**Comment by ZarshaB** [comment]
1) Footer should be at bottom at this page.
![image](https://user-images.githubusercontent.com/35685146/35269714-a7de02e4-004e-11e8-9e13-10097b9c4761.png)

**Comment by ZarshaB** [comment]
2) There should be next button for guide user which fields to be filled.
![image](https://user-images.githubusercontent.com/35685146/35269756-bdf68934-004e-11e8-91af-93905abba0d5.png)

**Comment by ZarshaB** [comment]
3) Back button should not turn red.
![image](https://user-images.githubusercontent.com/35685146/35269774-d0c0b030-004e-11e8-90b6-c9a78d255cd1.png)

**Comment by ZarshaB** [comment]
4) It should highlight field with red on clicking on "Save" button without filling form.
![image](https://user-images.githubusercontent.com/35685146/35269810-ec009112-004e-11e8-8e6b-65877a332156.png)

**Comment by ZarshaB** [comment]
5) According to requirement document there should be three fields on first page : Ad Title, Description and Pictures (mandatory to upload 1 picture and maximum of 5 pictures).
Second page will have all other fields as agreed in product backlog Car Make, Model, Year, Body Type, Mileage, Price, Transmission Type, Color, Fuel Type, Regional Specs, Warranty, Service History, Price, Location and City.

**Comment by ZarshaB** [comment]
6) Edit option is not given to user for image uploading. User should be able to edit image after uploading before saving form.

**Comment by ZarshaB** [comment]
7) No terms and conditions checkbox is there at bottom of page. As there should be a checkbox of terms and conditions.

**Comment by ZarshaB** [comment]
8) Uploaded ad does not appear anywhere in My Account.

**Comment by ZarshaB** [comment]
9) No message appears after uploading ad. According to requirement this message should appear after user has uploaded ad:
"Thanks for submitting the ad. Our car gurus will now be doing “free” evaluation of your ride and will get back to you within 12 hours.
And since you have already decided to sell your car, then why not try your luck here (hyperlink) for your next ride. Happy Shopping!!!"

**Comment by ZarshaB** [comment]
10) No email is sent after uploading ad to tell user that his ad is live.

**Comment by zohaibqadir** [comment]
2. Fixed
![2](https://user-images.githubusercontent.com/19669736/35275088-5938060a-0060-11e8-98e6-52bf2b5a8893.png)

**Comment by zohaibqadir** [comment]
3. Fixed
![3](https://user-images.githubusercontent.com/19669736/35275157-a3d849a4-0060-11e8-81ef-820adc363881.png)

**Comment by zohaibqadir** [comment]
4. Fixed
![4](https://user-images.githubusercontent.com/19669736/35275201-ceea278e-0060-11e8-8ad5-eaf49cccae8e.png)

**Comment by zohaibqadir** [comment]
6. FIXED: User can edit / replace the add by clicking the upload image button again

**Comment by zohaibqadir** [comment]
7. Fixed
![5](https://user-images.githubusercontent.com/19669736/35275493-c0003af0-0061-11e8-9f2a-9ef8646d91aa.png)

**Comment by zohaibqadir** [comment]
5. Issue has to discussed with Sir Tanzeel as it is looking good according to design

**Comment by zohaibqadir** [comment]
8. Fixed
![6](https://user-images.githubusercontent.com/19669736/35275583-13fcb5ca-0062-11e8-8ff9-60c6a1037d80.png)

**Comment by zohaibqadir** [comment]
9. Fixed
![7](https://user-images.githubusercontent.com/19669736/35275777-a5992fcc-0062-11e8-9b34-df0f5dce1445.png)

**Comment by zohaibqadir** [comment]
10. Fixed 
     Email will be send once admin will approve/activate the ad

**Comment by ZarshaB** [comment]
9) Message should be 
 "Thanks for submitting the ad. Our car gurus will now be doing “free” evaluation of your ride and will get back to you within 12 hours.
And since you have already decided to sell your car, then why not try your luck here (hyperlink) for your next ride. Happy Shopping!!!" 
As mentioned in document.

**Comment by ZarshaB** [comment]
11) If user clicks on "Place your Ad" button without login then after login user should be redirected to "Upload Ad" page.

**Comment by ZarshaB** [comment]
12) On clicking on "Place your Ad" button without login, it redirects user to login page but also shows error message. It should redirect to login page without error message. 
![image](https://user-images.githubusercontent.com/35685146/35326464-94a584c0-0118-11e8-9022-92d5894bacdb.png)

**Comment by ZarshaB** [comment]
13) It gives me error if I enter price having 111111 
![image](https://user-images.githubusercontent.com/35685146/35326733-5f77f390-0119-11e8-8455-1bf82583799f.png)

**Comment by ZarshaB** [comment]
14) On clicking on Back button it brought me to this page after I had submitted the form. 
![image](https://user-images.githubusercontent.com/35685146/35327044-4416b888-011a-11e8-9f25-61729eb84684.png)

**Comment by ZarshaB** [comment]
15) It should not take numbers in color field.
![image](https://user-images.githubusercontent.com/35685146/35327162-b7bcc868-011a-11e8-994c-fda4888cb1ce.png)

**Comment by ZarshaB** [comment]
16) Live Ad email template.
Spelling mistake for "Listing". Images are not required for this email. Please remove background color for weladela.com link and only make text orange to maintain consistency. 
And also All links of weladela.com are not redirecting to dummy site. 
Also name of Button is "View Ad" instead of "View Your Ad".
![image](https://user-images.githubusercontent.com/35685146/35327937-b3fb2740-011c-11e8-8b19-55845db39461.png)

Template:
![image](https://user-images.githubusercontent.com/35685146/35328043-f50e72e6-011c-11e8-9de7-9dd2ed68ae04.png)

**Comment by ZarshaB** [comment]
17) Subject of email should be "Your Ad is live on weladela.com" instead of "Your ad is now live"
![image](https://user-images.githubusercontent.com/35685146/35331397-0bcfb2ae-0129-11e8-98c1-d2aea2359e47.png)

**Comment by ZarshaB** [comment]
18) Please change "Ad name" to "Ad title". And also set limit for title.
![image](https://user-images.githubusercontent.com/35685146/35429875-bbaa4d82-0297-11e8-9288-534e35cef5aa.png)

**Comment by ZarshaB** [comment]
19) Please write Ad with Price. Price (AD)
![image](https://user-images.githubusercontent.com/35685146/35429896-d3784f2c-0297-11e8-8825-e76e523d715c.png)

**Comment by ZarshaB** [comment]
20 Please make model year, fuel type and Regional specs a drop down.
![image](https://user-images.githubusercontent.com/35685146/35429946-106ebe5c-0298-11e8-8dc6-1bdd21355d1f.png)

**Comment by ZarshaB** [comment]
21) Please make warranty and transmission type radio buttons. Values of Radio buttons would be:
yes, no, does not apply.
![image](https://user-images.githubusercontent.com/35685146/35430006-4215afc4-0298-11e8-95ef-93cc1ebc06a5.png)

**Comment by ZarshaB** [comment]
22) Please make Service history radio button. Values of radio button would be:
yes, no
![image](https://user-images.githubusercontent.com/35685146/35430038-6200e0ba-0298-11e8-818f-d8923f1ca329.png)

**Comment by ZarshaB** [comment]
23) Price should not accept decimal.
![image](https://user-images.githubusercontent.com/35685146/35430155-dd23d888-0298-11e8-8e10-1a4d3529be94.png)

**Comment by ZarshaB** [comment]
24) At bottom of page please mention this:
By clicking on Proceed, I agree to the following: - 

•	I’m the owner of the car and will present all the necessary identification and ownership documents at the time of ownership transfer.
•	Once the draw is concluded, I’ll transfer in Buyer’s name within 7 days of the draw.
•	In case the car fails to pass the test, its my responsibility to have the car repaired as pointed out in report.
•	In case I change my mind about selling the car or manage to sell the car elsewhere, I’ll immediately notify weldela.com about the same well before the draw date.

I hereby also acknowledge that I have read, understood and agreed to all other terms and conditions(hyperlink) and will adhere to them unconditionally.

**Comment by ZahidRavian** [comment]
These issues are fixed
9,12,15,17,18, 19, 20, 21, 22, 23, 24

**Comment by ZarshaB** [comment]
12) Not fixed. Please change error message as mentioned.

**Comment by ZarshaB** [comment]
18) Field name is changed which is correct.
Please also change field name for error message.
![image](https://user-images.githubusercontent.com/35685146/35500851-b470ab88-04f9-11e8-9346-27aa0d0ccad6.png)

**Comment by ZarshaB** [comment]
20) Not fixed.
Body type is missing =  Hatchback in drop down.

**Comment by ZarshaB** [comment]
9) Please remove hyperlink word and make "here" hyperlinked by changing color.
![image](https://user-images.githubusercontent.com/35685146/35501056-8a959c96-04fa-11e8-8fd5-8e3e77db5d3f.png)

**Comment by ZarshaB** [comment]
24) Not fixed.

**Comment by ZarshaB** [comment]
25) Please make weladela.com of Terms and conditions, as hyperlinked to site.

**Comment by ZarshaB** [comment]
26) Please change it to "Car make" instead of "maker".
![image](https://user-images.githubusercontent.com/35685146/35516995-1194681a-052f-11e8-8340-a335f42d3de1.png)

**Comment by ZarshaB** [comment]
27) Please make it Price is required.
![image](https://user-images.githubusercontent.com/35685146/35517828-6b993032-0531-11e8-9b6a-f5071df969f0.png)

**Comment by ZarshaB** [comment]
28) Please make it "Main Image is required."
![image](https://user-images.githubusercontent.com/35685146/35518234-cb0117aa-0532-11e8-859b-33e87bb0f324.png)

**Comment by ZarshaB** [comment]
29) Please make it " Please check the terms and conditions checkbox."
![image](https://user-images.githubusercontent.com/35685146/35518301-fe961ec6-0532-11e8-989b-04bc9d1e0e81.png)

**Comment by ZarshaB** [comment]
30) If I do not select/fill the required fields and enter Save button by only selecting required image and checking the checkbox then It is saving my ad.
And If I fill some of required fields and then selecting required image and checking the checkbox then it takes me to login page and also makes me logout.

**Comment by ZahidRavian** [comment]
These issues are fixed. please check and delete them from github
12, 18, 20, 9

**Comment by ZarshaB** [comment]
12) Please remove "Forgot Password" from this error message.
![image](https://user-images.githubusercontent.com/35685146/35556340-c832e238-05c3-11e8-899a-4afc0f84f242.png)

**Comment by ZahidRavian** [comment]
These issues are fixed. Please check and remove them from github
12, 24, 25, 26, 27, 28, 29, 30

**Comment by ZarshaB** [comment]
28) Please make it " Main Image is required" instead of "Main image".
![image](https://user-images.githubusercontent.com/35685146/35575929-897f6f20-05ff-11e8-8be5-e5dca142ebb1.png)

**Comment by asifjans** [comment]
@ZarshaB  Please remove fixed task

**Comment by ZarshaB** [comment]
Sir @asifjans removed.

**Comment by asifjans** [comment]
@ZarshaB  Where "Hyperlink" will redirect user?

**Comment by ZarshaB** [comment]
Sir hyperlink is redirecting to correct place i.e. "View Cars" page.

**Comment by ZarshaB** [comment]
18) If I don't enter ad title and also do not fill the fields of description and without uploading images click on "Save" button, then it redirects me to the back page. When I enter title and Click on Save button then instead of taking me to next page i.e. of description, it takes me to images page.
