### ISSUE TITLE
Client's Feedback

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#71]
1. o	Please make the movement of text very subtle. Instead of making it jump and bounce around, lets keep it simple. **(anum)**
2. o	In How it Works section on homepage, the button colors have been interchanged for buyer and seller. **(anum)**
3. o	In How it Works section on homepage, the functionality of the Buyer and Seller button is not correct. If it is already displaying the buyer side of HIW and I still click the buyer button, it changes the slides to seller section.  **(anum)**
4. o	Please minimize the timer block size by at least 20% **.(haider)**
5. o	On homepage, timer is working only on one car ad. **(Fixed)**
6. o	The quick view button is getting hidden if the picture background is is dark. **(Haider)**
7. o	In car view section, please refer to second car ad. Whole ad and its Buy now Button has moved down due to lengthy Ad Title. So please ensure that regardless the length of Ad Title, the alignment should remain same. If the title is lengthy, then you can show some part of it and hide rest of it on View cars page. **(Haider)**
8. o	When a specific car ad is opened, the image is not getting enlarged when I click on the picture.**(Zahid)**
9. o	After applying filters, when search results are displayed, the filters that have been applied disappear. They should remain there in tact. **(Zahid)**
10. o	In year range filters, when I select a specific starting year, then the options in ending year should only the years preceding that particular year. For example, if I select 2012 in first drop down, then in second drop down, the options that appear should be 2013,14,15,16,17 and 18. **(Zahid)**
11. o	There should be a Reset button for resetting filters **(Zahid)**
12. o	Please counter check all the spellings for all car makes and models. I randomly checked for Aston Martin and in there model type, spelling for Zagato for somewhat different.
**(Zarsha/Shayaan)**
13. o	The price filter btton is difficult to operate. I tried to set it at 200 but couldn't do it depsite trying five times. **(Zahid box ad dubi...)**
14. o	The max value of price filter button should go up to 1500. **(Zahid)**
15. o	When price filter is applied for certain value and results are displayed, the bar gets reset to extreme ends whereas value remains within the specified range. Please make necessary rectifications. **(Zahid)**
16. o	In car details, the mileage should be in KMs and not KM/L **(Zahid)**
17. o	In warranty and service history, when we select any value, it will display that value alone and the customer will not have any clue what that value is for. For example, in Service history, when I choose Yes, the option will be displayed as Yes only while not mentioning what this Yes is for. It is very confusing. Same can be observed in other fields as well. So I'd recommend that  we switch to radio buttons or check boxes for Transmission Type, Fuel Type, Warranty, regional Specs and Service History. **(Zahid)**
18. o	When quick view button is clicked and ad is displayed, the cross button at the top is touching the Ad title. Additionally, the button is not a perfect circle.  **(Haider)**

**Comment by asifjans** [comment]
4, 6, 7, 18 (Fixed)

**Comment by Anum444** [comment]
1 , 2 , 3 (Fixed)

**Comment by ZahidRavian** [comment]
These issues are fixed.
9, 11, 14, 16
13. As per discussion with Sir Tanzeel this issue is already fixed.

**Comment by ZarshaB** [comment]
1) Slider is taking time to load.
2 ,3) Fixed but if I click anywhere then both buttons get unfilled.
4) Fixed.
6) Fixed for View Cars page but not on "Our Featured Cars" of Home page.
7) Fixed for View Cars but for "Car Detail" page going out of layout.
![image](https://user-images.githubusercontent.com/35685146/35686323-d81cb068-078d-11e8-97c0-ec6b1296df80.png)
9) Car Model's value disappears on clicking on "Search".
11,12,13,14,16 >> Fixed

**Comment by ZarshaB** [comment]
Fixed >> 3 , 4 ,7,11, 12, 13, 14, 16, 18

Not Fixed:
1 >> Text is not moving that is okay but Slider stops on hover.
3 >> Fixed but if I click anywhere then both buttons get unfilled.
5 >> Timer is working but time is not correct
6 >> Images are not visible on Home page so could not check there.
![image](https://user-images.githubusercontent.com/35685146/35725785-6213d22e-0824-11e8-97a5-71f9a5820801.png)
8 >> Not Fixed
9 >> Car Model's value disappears on clicking on "Search". And also if I go to next page of searched results then filters got disappear.
10 >> Second drop down should not include the year mentioned in first drop down. Second drop down should only include the proceeding years of one drop down.
![image](https://user-images.githubusercontent.com/35685146/35725674-030fb388-0824-11e8-9b90-a81229e66bfa.png)
15 >> Not Fixed
17 >> Not Fixed

**Comment by ZarshaB** [comment]
**NOT FIXED**
5 >> Timer is not showing correct hours.
6 >> Fixed for View Cars but not on Home page.
![image](https://user-images.githubusercontent.com/35685146/35739497-97c7218a-0853-11e8-8aab-89ed81b24f1c.png)
![image](https://user-images.githubusercontent.com/35685146/35739520-a917c4da-0853-11e8-974b-1089f008b88b.png)
8 >> Not Fixed
15 >> Not Fixed

**Comment by ZarshaB** [comment]
**Not Fixed:
5, 15**

**Comment by asifjans** [comment]
5-On homepage, timer is working only on one car ad. **( Not Fixed)**
15- When price filter is applied for certain value and results are displayed, the bar gets reset to extreme ends whereas value remains within the specified range. Please make necessary rectifications. **(Zahid)**

**Comment by asifjans** [comment]
5 ) Fixed
15 ) Fixed

**Comment by ZarshaB** [comment]
5) When timer starts, hours should be 23.

Other Issues are fixed.
