### ISSUE TITLE
Sprint 1 Pending task

### ISSUE THREAD

**Issue by asifjans** [asifjans/Inovedia#72]

**Comment by ZarshaB** [comment]
**Home Page**
Social Icons state on hover and by default.
Testimonials slider.
Footer Alignment and Download Link Alignment.
Search bar outline.

**Comment by ZarshaB** [comment]
**View Cars Page**
Timer.
Watch icon label.
Add to Favourites instead of Add to Favourite.
Searching Issues.
Tickets Sold.
Time Left on Pop up.
Sort By.
When a specific car ad is opened, the image is not getting enlarged when I click on the picture.

**Comment by ZarshaB** [comment]
**Car Detail Page**
On clicking on "Buy Now" button without login, user should be redirected to "Car Detail" page after user has logged in.
Timer.
When user clicks on "Buy Now" button then admin's email is sent to user instead of Admin. Also subject of email in incorrect.
Remaining Filters Issues.
Favourites icon not working.
Buttons alignment.

**Comment by ZarshaB** [comment]
**Order Summary Page**
Billing Address validation same as other pages validation.
Change Country to city.
Reward Points button Functionality.
Removing extra text.

**Comment by ZarshaB** [comment]
**Login Page**
Facebook Login.

**Comment by ZarshaB** [comment]
**Register Page**
Captcha.
I have to select two times from DOB then errors disappears.
It should not accept Emirates Id less than the mentioned places. As now it is accepting if I only enter one digit. It should display error:
"Please enter valid Emirates Id."
Email error message correction.
Hear About Us field correction.

**Comment by ZarshaB** [comment]
**Upload Ad**
Message correction.
If I don't enter ad title and also do not fill the fields of description and without uploading images click on "Save" button, then it redirects me to the back page. When I enter title and Click on Save button then instead of taking me to next page i.e. of description, it takes me to images page.

**Comment by ZarshaB** [comment]
**Client's Feedback**
1,3,5,6,8,9,10,15,17 >> Issues Remaining

**Comment by ZarshaB** [comment]
**Email Templates**
Welcome Template = Images are not appearing
Forgot Your Password = Template is not appearing correctly
Buy Now Template is okay but Subject is not correct
Live Ad link color.

**Comment by ZarshaB** [comment]
**Terms and Conditions**
Main Terms and Conditions are not updated and weladela.com is not linked and correct.

**Comment by ZarshaB** [comment]
**Responsive Issues**

**Comment by Anum444** [comment]
Not Fixed yet

**Comment by ZarshaB** [comment]
**Not Fixed:**

**Home:**
Alignment of "Download App Link" is not correct it should be in centre.
How It Works images should not be clickable.
Lear More buttons and "Powered by Inovedia" should be aligned to "Place your Ad" buttons.
Left Alignment of Images ( How it works) , Testimonials and social icons should be aligned.
Testimonials should move continuously.
Taking user to "Our Featured Cars" section but if screen is zoom out then it does not take to that section.

**Comment by ZarshaB** [comment]
***Not Fixed:**

**View Cars:**
1) It should be " 1 Page" instead of "1 Pages".
![image](https://user-images.githubusercontent.com/35685146/35796020-f0a5e504-0a7c-11e8-8f9f-bbe7b0e77c39.png)

2) Timer should display 23 hours as time starts.
3) On clicking on "Add to Favourites" , pop up should be displayed on current page instead of redirecting it to Home page.
4) On clicking on Favourites if not login then after login user should be redirected to View Cars page.
5) Please make it first "Favourite" and then "watch" icon as it is on Home page.
![image](https://user-images.githubusercontent.com/35685146/35796266-cf45c842-0a7d-11e8-91fb-31df858c8548.png)

**Comment by ZarshaB** [comment]
**Not Fixed:**
**Car Detail:**
1) Favourites button is not working.
![image](https://user-images.githubusercontent.com/35685146/35796506-93d4c3d4-0a7e-11e8-9b40-9387a67ff854.png)

2) Buttons alignment is not same.
![image](https://user-images.githubusercontent.com/35685146/35796529-aa63ddec-0a7e-11e8-83e0-ece3d256c68f.png)

**Comment by ZarshaB** [comment]
**Not Fixed:**
**Order Summary:**

1) Please make it's validation same as we are using for all other pages.
![image](https://user-images.githubusercontent.com/35685146/35796627-fc7de8d4-0a7e-11e8-9f69-c551bf93de3c.png)
2) Button should be disabled if user does not have reward points. Also not functional.
![image](https://user-images.githubusercontent.com/35685146/35796652-0bf8263a-0a7f-11e8-9294-84e8c3e1e5bf.png)
3) Please make it City.
![image](https://user-images.githubusercontent.com/35685146/35796670-19815510-0a7f-11e8-9a8c-ed1e5d22c86b.png)
4) Heading is not correct.
![image](https://user-images.githubusercontent.com/35685146/35796694-31d9932a-0a7f-11e8-96bd-5cc49962a32b.png)
5) Remove button turns to red on clicking on it.
![image](https://user-images.githubusercontent.com/35685146/35796729-46592bd0-0a7f-11e8-8a4d-3a05f07a32dd.png)

**Comment by ZarshaB** [comment]
**Not Fixed:
Login Page**

1) Facebook Login is missing.

**Comment by ZarshaB** [comment]
**Not Fixed:
Register Page**

1) I have to select two times from DOB then errors disappears.
![image](https://user-images.githubusercontent.com/35685146/35797071-5e005ef6-0a80-11e8-84ea-060b6ca4d9ae.png)
2) It should not accept Emirates Id less than the mentioned places. As now it is accepting if I only enter one digit. It should display error:
"Please enter valid Emirates Id."
![image](https://user-images.githubusercontent.com/35685146/35797080-68835428-0a80-11e8-8bb6-79f291990bb6.png)

**Comment by ZarshaB** [comment]
**Functional Issues**

Home >> 2,5,6
View Cars >> 2,3,4,6
Car Detail >> 1
Order Summary >> 1,2
Login >> 1
Register >> 1,2

**Comment by ZarshaB** [comment]
**Not Fixed
Email Templates**
Welcome Template = Images are not appearing 
Forgot Your Password = Template is not appearing correctly

**Comment by ZarshaB** [comment]
**Remaining Responsive Issues.**

**Comment by ZahidRavian** [comment]
These issues are fixed now. Please check and close them.
Home >> 2, 5
View Cars >> 2,3,6
Car Detail >> 1,2,3
Order Summary >> 2

**Comment by ZarshaB** [comment]
Place your Ad:
When I submit ad then on clicking on Save button it redirects me to blank page.
![image](https://user-images.githubusercontent.com/35685146/35812751-ae6486dc-0ab3-11e8-8b43-7f774437135e.png)

**Comment by ZarshaB** [comment]
I have removed issues those are fixed from "Not Fixed". The issues those are not fixed are only there.
And also "Reward Points button" would be verified when we'll have reward points in account. 
Same is the case with tickets sold and Payment gateway testing.
Also not able to upload my ad.

**Comment by ZarshaB** [comment]
Not Fixed:
Home >> 1,2,3,4,5,6,7,8
View Cars >> 1,2,3,4
Car Detail >> 1
Order Summary >> 1,2,3,4,5,6
Login >> 1
Register >> 1,2

**Comment by ZarshaB** [comment]
**Fixed Issues:** **( Good work Guys!! 👍 Keep it up!)** 
Home >> 2 Issues are fixed
View Cars >> 2 Issues are Fixed.
Login >> Facebook login button is available and it would be working when Fb will approve.

**Not Fixed:**
Home >> 2,3,4,5,6,8
View Cars >> 10 >> It is fixed for One page that is correct but if we have more than one page then it will still show one page.It should display (page/pages) or something like that.
![image](https://user-images.githubusercontent.com/35685146/35852577-1afef072-0b4d-11e8-9353-4d36bdc9e2ae.png)
Car Detail >> 12
Order Summary >> 14,15,16,18
Register >> 21,21

**New Logged:**
Home >> 9
View Cars >> 11
Car Detail >> 13
Order Summary >> 19

**Functional Issues:**
Home >> 4
Order Summary >>19
Register >> 22

**Comment by ZarshaB** [comment]
**Email Template:**
Place your Ad template is okay.
Verify you Account template is okay.
Rest Template is okay only "Reset" button is not appearing.
![image](https://user-images.githubusercontent.com/35685146/35854349-f0041488-0b51-11e8-8ad9-4da3d7d3e416.png)
IN Welcome email:
Images are not coming and on taking cursor on email or "View Ad" they disappears.
![image](https://user-images.githubusercontent.com/35685146/35854668-c7ef34a4-0b52-11e8-97c4-877a780cded3.png)

**Comment by ZarshaB** [comment]
**Upload Ad** 
19) When I click on "Next" after giving title then on next page it displays error on all required fields. It should only display error if I click on "Next" button without filling required fields.

**Comment by ZarshaB** [comment]
**Login** 
20) **Facebook login :** If user login with Facebook then Welcome email should be sent to him.

**Comment by ZarshaB** [comment]
**Home:**
21) It should also become bold on selection and become semi bold on selecting other button.
![image](https://user-images.githubusercontent.com/35685146/35856689-8e2f77aa-0b58-11e8-8fcf-b70b22ca3477.png)

**Comment by ZarshaB** [comment]
**Car Detail**
24 >> Alignment is not correct.
![image](https://user-images.githubusercontent.com/35685146/35861407-67f10dcc-0b69-11e8-9b0c-a63157baaf92.png)

Template:
![image](https://user-images.githubusercontent.com/35685146/35861441-8bab070e-0b69-11e8-916a-ad729da9273f.png)

**Comment by ZarshaB** [comment]
**Home:**
25 >> Please also make it unclickable for "Seller" also.
![image](https://user-images.githubusercontent.com/35685146/35861755-f80430b4-0b6a-11e8-8b33-c5fe5821edf6.png)

**Comment by ZarshaB** [comment]
**View Cars**
26 >> Please Remove line below AED and reduce space same as it is on Home page.
![image](https://user-images.githubusercontent.com/35685146/35861849-5ddbe274-0b6b-11e8-98e8-5d37ab55dcd2.png)

On Home Page:
![image](https://user-images.githubusercontent.com/35685146/35861864-71068d9a-0b6b-11e8-8fe2-07f7f6990539.png)

**Comment by ZarshaB** [comment]
**View Cars**
27) Quantity should not allow to enter alphabets.
![image](https://user-images.githubusercontent.com/35685146/35909981-f4ba61ec-0c16-11e8-8648-108fc4df14d9.png)

**Comment by ZarshaB** [comment]
**Place your Ad:**
28) Redirecting to blank page on submitting ad.

**Comment by ZarshaB** [comment]
**Order Summary Page:**
29) It is redirecting me to blank page on clicking on "Checkout" button.

**Comment by ZarshaB** [comment]
Order Summary Page:
30) For long title, complete quantity is not appearing in field.
![image](https://user-images.githubusercontent.com/35685146/35911361-71e239ca-0c1b-11e8-9cf2-9300dd72fa28.png)

**Comment by ZarshaB** [comment]
**Not Fixed:
Register Page**

17>>  I have to select two times from DOB then errors disappears.
![image](https://user-images.githubusercontent.com/35685146/35797071-5e005ef6-0a80-11e8-84ea-060b6ca4d9ae.png)
18>> It should not accept Emirates Id less than the mentioned places. As now it is accepting if I only enter one digit. It should display error:
"Please enter valid Emirates Id."
![image](https://user-images.githubusercontent.com/35685146/35797080-68835428-0a80-11e8-8bb6-79f291990bb6.png)

19>> Captcha should display error as a required field if I click on Register without filling form. It only displays error if all other fields are filled.
![image](https://user-images.githubusercontent.com/35685146/35960671-6648ed64-0ccc-11e8-8e7c-b397b84893eb.png)

**Comment by ZarshaB** [comment]
**Not Fixed**
**Email Template:**
Place your Ad template is okay.
Verify you Account template is okay.
Rest Template is okay only "Reset" button is not appearing.
![image](https://user-images.githubusercontent.com/35685146/35854349-f0041488-0b51-11e8-8ad9-4da3d7d3e416.png)
IN Welcome email:
Images are not coming and on taking cursor on email or "View Ad" they disappears.
![image](https://user-images.githubusercontent.com/35685146/35854668-c7ef34a4-0b52-11e8-97c4-877a780cded3.png)

**Comment by ZarshaB** [comment]
**My Profile:**
Gender, DOB, Hear About Us Fields are missing.

Spacing between Password and Nationality is very less.
![image](https://user-images.githubusercontent.com/35685146/35963840-dd6770f4-0cd7-11e8-8e25-246586669b8b.png)

**Comment by ZarshaB** [comment]
**FAQs:**
It is FAQs not FAQ's.
![image](https://user-images.githubusercontent.com/35685146/35964392-74901c32-0cd9-11e8-95ec-c1c7dd94a39f.png)

**Comment by ZarshaB** [comment]
**Contact Us:**
Images are stretched.
Spacing is not correct.
Button is very small.
It should be Email Id.
It should be bold.
![image](https://user-images.githubusercontent.com/35685146/35964480-ac9afd54-0cd9-11e8-80d7-0f00753fce64.png)
![image](https://user-images.githubusercontent.com/35685146/35964490-b36f2f1a-0cd9-11e8-9688-720074fbb295.png)

**Template:**
![image](https://user-images.githubusercontent.com/35685146/35964508-c06a2a44-0cd9-11e8-935c-7c6448ea8c54.png)

**Comment by ZarshaB** [comment]
**View Cars** 
**Not Fixed:**
1>> It is fixed for One page that is correct but if we have more than one page then it will still show one page.It should display (page/pages) or something like that.
![image](https://user-images.githubusercontent.com/35685146/35852577-1afef072-0b4d-11e8-9353-4d36bdc9e2ae.png)

2>> Space is reduced for minutes .Please also remove it for Hours in Car detail page and pop ups.
![image](https://user-images.githubusercontent.com/35685146/35968495-d9b33bf6-0ce5-11e8-9d77-6e4ad9e129e7.png)


Template:
![image](https://user-images.githubusercontent.com/35685146/35861540-ea601910-0b69-11e8-86ea-282640a40bfb.png)

3>> Please Remove line below AED and reduce space same as it is on Home page.
![image](https://user-images.githubusercontent.com/35685146/35861849-5ddbe274-0b6b-11e8-98e8-5d37ab55dcd2.png)

On Home Page:
![image](https://user-images.githubusercontent.com/35685146/35861864-71068d9a-0b6b-11e8-8fe2-07f7f6990539.png)

4) Quantity should not allow to enter alphabets.
![image](https://user-images.githubusercontent.com/35685146/35909981-f4ba61ec-0c16-11e8-8648-108fc4df14d9.png)

**New Logged:**
5>> It should not be editable.
![image](https://user-images.githubusercontent.com/35685146/35968574-1858ef22-0ce6-11e8-97d7-712963142350.png)

**Comment by ZarshaB** [comment]
**Car Detail
Not Fixed:**

1>> Filters should be filled with that specific car's information.
10) When it clicks on "Buy Ticket" without login then it redirects to login page. It should also display some error message on login page as it displays for others. Like "Please Login in order to Buy Ticket".
![image](https://user-images.githubusercontent.com/35685146/35852009-825dbe8a-0b4b-11e8-9732-87b335446e26.png)

2 >> Alignment is not correct.
![image](https://user-images.githubusercontent.com/35685146/35861407-67f10dcc-0b69-11e8-9b0c-a63157baaf92.png)

Template:
![image](https://user-images.githubusercontent.com/35685146/35861441-8bab070e-0b69-11e8-916a-ad729da9273f.png)

**Comment by ZarshaB** [comment]
**Not Fixed:**
**Order Summary:**

1>> Please make it's validation same as we are using for all other pages.
![image](https://user-images.githubusercontent.com/35685146/35796627-fc7de8d4-0a7e-11e8-9f69-c551bf93de3c.png)
12>> Please make it City.
![image](https://user-images.githubusercontent.com/35685146/35796670-19815510-0a7f-11e8-9a8c-ed1e5d22c86b.png)

2>>  Remove button turns to red on clicking on it.
![image](https://user-images.githubusercontent.com/35685146/35796729-46592bd0-0a7f-11e8-8a4d-3a05f07a32dd.png)
3>>  **When I add anything in cart while I'm logged in and without checkout I log out then again logged in then item should be remained in the cart. (Low Priority)**
4>>  Checkout button should not turn to green on clicking, it should have same effect as other buttons have.
5>> It should not allow me to buy tickets more than 750 for any car.
![image](https://user-images.githubusercontent.com/35685146/35852393-96a3df9a-0b4c-11e8-8690-3098095dd612.png)

**Comment by ZarshaB** [comment]
Not Fixed.
**Upload Ad** 
1) When I click on "Next" after giving title then on next page it displays error on all required fields. It should only display error if I click on "Next" button without filling required fields.

**Comment by ZarshaB** [comment]
**Login** 
1) **Facebook login :** If user login with Facebook then Welcome email should be sent to him.

**Comment by ZarshaB** [comment]
Not Fixed.
Home: 
1>>  Learn More buttons and "Powered by Inovedia" should be aligned to "Place your Ad" buttons.
2>>  Left Alignment of Images ( How it works) , Testimonials and social icons should be aligned.
3>>  Taking user to "Our Featured Cars" section but if screen is zoom out then it does not take to that section.
4 >> Drop down is going out of layout.
![image](https://user-images.githubusercontent.com/35685146/35802294-580cf476-0a91-11e8-9e7b-9974f54268e3.png)
5>> Button's Text should also become bold on selection and become semi bold on selecting other button.
![image](https://user-images.githubusercontent.com/35685146/35856689-8e2f77aa-0b58-11e8-8fcf-b70b22ca3477.png)
6>> Header Jerks.

7>> Alignment is correct but It's size has become very small.
![image](https://user-images.githubusercontent.com/35685146/35856873-1df823dc-0b59-11e8-96d4-5853d95fb2d1.png)

8 >> Please also make it unclickable for "Seller" also.
![image](https://user-images.githubusercontent.com/35685146/35861755-f80430b4-0b6a-11e8-8b33-c5fe5821edf6.png)

**Comment by ZarshaB** [comment]
**Remaining Responsive Issues.**
https://github.com/asifjans/Inovedia/issues/61

**Comment by ZarshaB** [comment]
View Car:
Every new car added is coming in first line and all other cars are appearing on other line.
![image](https://user-images.githubusercontent.com/35685146/36024550-e0508f6e-0db1-11e8-8598-98af569941d7.png)

**Comment by ZarshaB** [comment]
In Welcome Email Template images are now appearing but there is alignment issue and also email and View Ad on hover disappears.
![image](https://user-images.githubusercontent.com/35685146/36031251-f071caec-0dcb-11e8-919e-32b451e46356.png)

**Comment by ZarshaB** [comment]
**Functional:**
Register >> 18
View Cars >> 4,5
Car Detail >> 3
Order Summary >> Reward points check and issue 4
Upload Ad >> 1
Login >> 1

**Comment by ZarshaB** [comment]
On selected page menu should be highlighted like this.
![image](https://user-images.githubusercontent.com/35685146/36062336-45009668-0e8c-11e8-99ca-3fb06a068c82.png)

**Comment by ZarshaB** [comment]
**Email Templates**

Verify your Account Template is okay.
Welcome Email Template is okay only alignment of ads is not correct.
![image](https://user-images.githubusercontent.com/35685146/36087681-735b4e9e-0ff5-11e8-84c1-01795d99d4e8.png)

**Comment by ZarshaB** [comment]
**Login**
1) It is sending me welcome email every time I logged in. It should only send welcome email if during registration email is not sent like in case of login from Facebook.

**Comment by ZarshaB** [comment]
**Home:**
1) On drop down nothing is visible and everything appears blank.
![image](https://user-images.githubusercontent.com/35685146/36089299-ffccf1be-0ffc-11e8-866b-4b8db5fd62ca.png)
1>>  Learn More buttons and "Powered by Inovedia" should be aligned to "Place your Ad" buttons.
2>>  Left Alignment of Images ( How it works) , Testimonials and social icons should be aligned.
3>>  Taking user to "Our Featured Cars" section but if screen is zoom out then it does not take to that section.
4 >> Drop down is going out of layout.
![image](https://user-images.githubusercontent.com/35685146/35802294-580cf476-0a91-11e8-9e7b-9974f54268e3.png)

6>> Header Jerks.

7>> Alignment is correct but It's size has become very small.
![image](https://user-images.githubusercontent.com/35685146/35856873-1df823dc-0b59-11e8-96d4-5853d95fb2d1.png)

**Comment by ZarshaB** [comment]
Register Page**

17>>  I have to select two times from DOB then errors disappears.
![image](https://user-images.githubusercontent.com/35685146/35797071-5e005ef6-0a80-11e8-84ea-060b6ca4d9ae.png)
18>> It should not accept Emirates Id less than the mentioned places. As now it is accepting if I only enter one digit. It should display error:
"Please enter valid Emirates Id."
![image](https://user-images.githubusercontent.com/35685146/35797080-68835428-0a80-11e8-8bb6-79f291990bb6.png)

**Comment by ZarshaB** [comment]
**Upload Ad** 
1) When I click on "Next" after giving title then on next page it displays error on all required fields. It should only display error if I click on "Next" button without filling required fields.

**Comment by ZarshaB** [comment]
**View Cars** 
**Not Fixed:**
1>> It is fixed for One page that is correct but if we have more than one page then it will still show one page.It should display (page/pages) or something like that.
![image](https://user-images.githubusercontent.com/35685146/35852577-1afef072-0b4d-11e8-9353-4d36bdc9e2ae.png)

2>> Space is reduced for minutes .Please also remove it for Hours in Car detail page and pop ups.
![image](https://user-images.githubusercontent.com/35685146/35968495-d9b33bf6-0ce5-11e8-9d77-6e4ad9e129e7.png)


Template:
![image](https://user-images.githubusercontent.com/35685146/35861540-ea601910-0b69-11e8-86ea-282640a40bfb.png)

3>>Line is removed that is okay. Please also reduce some space for AED.
![image](https://user-images.githubusercontent.com/35685146/36089688-022be72e-0fff-11e8-9cbc-35e3d8224cf0.png)


On Home Page:
![image](https://user-images.githubusercontent.com/35685146/35861864-71068d9a-0b6b-11e8-8fe2-07f7f6990539.png)

4) Quantity should not allow to enter alphabets.
![image](https://user-images.githubusercontent.com/35685146/35909981-f4ba61ec-0c16-11e8-8648-108fc4df14d9.png)

5>> It should not be editable.
![image](https://user-images.githubusercontent.com/35685146/35968574-1858ef22-0ce6-11e8-97d7-712963142350.png)

**Comment by ZarshaB** [comment]
**Car Detail
Not Fixed:**

1>> Filters should be filled with that specific car's information.


2 >> Alignment is not correct.
![image](https://user-images.githubusercontent.com/35685146/35861407-67f10dcc-0b69-11e8-9b0c-a63157baaf92.png)

Template:
![image](https://user-images.githubusercontent.com/35685146/35861441-8bab070e-0b69-11e8-916a-ad729da9273f.png)

3>> On clicking on "Buy Now" button I got a pop up and on clicking on that pop up I got message of Buy Now.
![image](https://user-images.githubusercontent.com/35685146/35979329-e4a03c16-0d09-11e8-9e1f-d985f7d970e3.png)

**Comment by ZarshaB** [comment]
**Not Fixed:**
**Order Summary:**

2>>  **When I add anything in cart while I'm logged in and without checkout I log out then again logged in then item should be remained in the cart. (Low Priority)**
3>>  Checkout button should not turn to green on clicking, it should have same effect as other buttons have.
4>> It should not allow me to buy tickets more than 750 for any car.
![image](https://user-images.githubusercontent.com/35685146/35852393-96a3df9a-0b4c-11e8-8690-3098095dd612.png)

5>>  For long title, complete quantity is not appearing in field.
![image](https://user-images.githubusercontent.com/35685146/35911361-71e239ca-0c1b-11e8-9cf2-9300dd72fa28.png)

6 >> If I update price then it reset Billing address field.

**Comment by ZarshaB** [comment]
**Home:**
1 >> Color is changed. 
![image](https://user-images.githubusercontent.com/35685146/36106029-0201d914-1038-11e8-9019-4827bac14288.png)

2>>  Learn More buttons and "Powered by Inovedia" should be aligned to "Place your Ad" buttons.
3>>  Left Alignment of Images ( How it works) , Testimonials and social icons should be aligned.
4>>  Taking user to "Our Featured Cars" section but if screen is zoom out then it does not take to that section.
5 >> Drop down is going out of layout.
![image](https://user-images.githubusercontent.com/35685146/35802294-580cf476-0a91-11e8-9e7b-9974f54268e3.png)

6>> Header Jerks.

7>> Alignment is correct but It's size has become very small.
![image](https://user-images.githubusercontent.com/35685146/35856873-1df823dc-0b59-11e8-96d4-5853d95fb2d1.png)

**Comment by ZarshaB** [comment]
**Register Page**

17>>  I have to select two times from DOB then errors disappears.
![image](https://user-images.githubusercontent.com/35685146/35797071-5e005ef6-0a80-11e8-84ea-060b6ca4d9ae.png)
18>> It should not accept Emirates Id less than the mentioned places. As now it is accepting if I only enter one digit. It should display error:
"Please enter valid Emirates Id."
![image](https://user-images.githubusercontent.com/35685146/35797080-68835428-0a80-11e8-8bb6-79f291990bb6.png)

**Comment by sammiullah** [comment]
Email Templates Both Issues resolved.

**Comment by ZarshaB** [comment]
**Upload Ad** 
1) When I click on "Next" after giving title then on next page it displays error on all required fields. It should only display error if I click on "Next" button without filling required fields.

**Comment by ZarshaB** [comment]
**Order Confirmation Email Template:**
Please move "Paid" stamp to left and make space between highlighted line.
![image](https://user-images.githubusercontent.com/35685146/36139802-ca21faf4-10c0-11e8-834e-1609723f4417.png)

**Template:**
![image](https://user-images.githubusercontent.com/35685146/36139812-d3811986-10c0-11e8-8bb2-4f81e0afe549.png)

**Comment by ZarshaB** [comment]
Email Templates:
Please change it to "onto" instead of "on to" in both "Reset password" and "Verify your Account" template.
![image](https://user-images.githubusercontent.com/35685146/36145254-a034f338-10d2-11e8-90b8-085b05e612b8.png)
